# Cambiar la tecla de prefijo de Ctrl+b a Ctrl+a
unbind C-b
set -g prefix C-Space
bind-key C-Space send-prefix
bind -n M-s setw synchronize-panes

unbind '"'
unbind %

bind h split-window -h   # h = horizontal (izquierda/derecha)
bind v split-window      # v = vertical (arriba/abajo)
